### ISSUE TITLE
Wrong parameter name for specifying config file in README?

### ISSUE THREAD

**Issue by daluu** [lixingcong/my-gfwlist#1]
You listed `dnsmasq --conf-dir=/tmp/gfwlist.conf` but should be `dnsmasq --conf-file=/tmp/gfwlist.conf` I believe. Using the original value, get error about accessing/finding the directory.

**Comment by lixingcong** [comment]
Thanks! fixed https://github.com/lixingcong/my-gfwlist/commit/afceb5b67cd64733396829079e2d932b558332ed
