### ISSUE TITLE
您好, 请问domains_blocked.txt是怎么生成的?

### ISSUE THREAD

**Issue by blog2i2j** [lixingcong/my-gfwlist#2]
您好, 请问domains_blocked.txt是怎么生成的?
有办法从gfwlist中自动生成domains_blocked.txt或者dnsmasq regex domain吗? 谢谢

**Comment by lixingcong** [comment]
暂无办法。domains_blocked.txt是手工输入的。。

你要是坚持使用gfwlist，可以用[Chrome插件SwitchyOmega](https://www.google.com/search?q=SwitchyOmega)

**Comment by blog2i2j** [comment]
明白了, 谢谢.
非常感谢你开发的dnsmasq regex, 已经用上了. 非常好用.
